package com.rijaldev.jetgithub.util

import com.rijaldev.jetgithub.data.local.entity.UserEntity

object GithubUserData {

    fun getDummyUsers() = listOf(
        UserEntity(
            id = 0,
            username = "alex",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/772?v=4",
            fullName = "Alex Gaynor",
            bio = "I program computers, and build teams that program computers, with a heavy focus on security",
            repositories = 525,
            followers = 8500,
            following = 38,
        ),
        UserEntity(
            id = 1,
            username = "biodranik",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/170263?v=4",
            fullName = "Alexander Borsuk",
            bio = "Cofounder at @organicmaps (offline mobile maps for travelers) and @VibroBox (Prescriptive Diagnostics for industrial equipment), creator of @mapsme app.",
            repositories = 51,
            followers = 227,
            following = 2,
        ),
        UserEntity(
            id = 2,
            username = "sverweij",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/4822597?v=4",
            fullName = "Sander Verweij",
            bio = "I should've learned to play the guitar",
            repositories = 26,
            followers = 258,
            following = 18,
        ),
        UserEntity(
            id = 3,
            username = "emilk",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/1148717?v=4",
            fullName = "Emil Ernerfeldt",
            bio = "Rust coder, creator of egui, CTO of rerun.io. Has worked with physics simulation, games, 3D scanning, and cyber security.",
            repositories = 65,
            followers = 3100,
            following = 4,
        ),
        UserEntity(
            id = 4,
            username = "chrisbanes",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/227486?v=4",
            fullName = "Chris Banes",
            bio = "A software engineer focused on all things UI",
            repositories = 46,
            followers = 17500,
            following = 3,
        ),
        UserEntity(
            id = 5,
            username = "jacogr",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/1424473?v=4",
            fullName = "Jaco",
            bio = "I build. Maintainer of @polkadot-js.",
            repositories = 89,
            followers = 1700,
            following = 1,
        ),
        UserEntity(
            id = 6,
            username = "brycedrennan",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/1217531?v=4",
            fullName = "Bryce Drennan",
            bio = "Creator of imaginAIry. Half-competent AI researcher. First Engineer at @CircleUp",
            repositories = 31,
            followers = 489,
            following = 37,
        ),
        UserEntity(
            id = 7,
            username = "zeke",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/2289?v=4",
            fullName = "Zeke Sikelianos",
            bio = "Machine learner at @replicate. Open source gardener. Previously @github, @electron, @npm, @heroku. he/him",
            repositories = 956,
            followers = 2500,
            following = 289,
        ),
        UserEntity(
            id = 8,
            username = "adamchainz",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/857609?v=4",
            fullName = "Adam Johnson",
            bio = "@django technical board member \uD83C\uDDEC\uD83C\uDDE7 @djangolondon co-organizer ✍ AWS/Django/Python Author and Consultant",
            repositories = 1300,
            followers = 3200,
            following = 155,
        ),
        UserEntity(
            id = 9,
            username = "dicodingacademy",
            type = "Organization",
            avatarUrl = "https://avatars.githubusercontent.com/u/22091590?s=200&v=4",
            fullName = "Dicoding Academy",
            bio = "-",
            repositories = 148,
            followers = 504,
            following = 0,
        ),
        UserEntity(
            id = 10,
            username = "ripienaar",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/82342?v=4",
            fullName = "R.I.Pienaar",
            bio = "Systems Architect, Automator, Coder.",
            repositories = 121,
            followers = 2400,
            following = 0,
        ),
        UserEntity(
            id = 11,
            username = "aler9",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/46489434?v=4",
            fullName = "Alessandro Ros",
            bio = "Software and robotics engineer, i deal with anything that can be modeled and controlled. Full-time @ AlmavivA, MSc @ PoliMi, AWS Certified",
            repositories = 43,
            followers = 402,
            following = 11,
        ),
        UserEntity(
            id = 12,
            username = "rfyiamcool",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/3785409?v=4",
            fullName = "fengyun.rui",
            bio = "march forward courageously ! Happy every day ! ",
            repositories = 218,
            followers = 4000,
            following = 431,
        ),
        UserEntity(
            id = 13,
            username = "obi1kenobi",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/2348618?v=4",
            fullName = "Predrag Gruevski",
            bio = "-",
            repositories = 70,
            followers = 198,
            following = 2,
        ),
        UserEntity(
            id = 14,
            username = "acheong08",
            type = "User",
            avatarUrl = "https://avatars.githubusercontent.com/u/36258159?v=4",
            fullName = "Antonio Cheong",
            bio = "Sleep deprived high school student",
            repositories = 80,
            followers = 1700,
            following = 61,
        ),
    )
}